version: 2.1

orbs:
  maven: circleci/openjdk:stretch


jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
   
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: /mvn test
  
  
workflows:
  maven_build :
    jobs:
    - build
    - test