version: 2.1

orbs:
  maven: circleci/maven@1.0.2


jobs:
  build:
    docker:
      - image: circleci/maven@1.0.2
    steps:
      - checkout
   
  test:
    docker:
      - image: circleci/maven@1.0.2
    steps:
      - checkout
      - run: /mvn test
  
  
workflows:
  maven_build :
    jobs:
       - build
       - test